version: "3.9"
services:

    adguard:
        image: adguard/adguardhome:latest
        container_name: adguard
        hostname: adguard
#        user: 1000:1000 #put your docker used ID (UID) and group ID (GID) here!
        domainname: local
        mac_address: 00:fa:c0:fa:c0:aa
        cap_add:
            - NET_ADMIN
        networks:
          macvlan_network:
            ipv4_address: ${ip}  #ip of your adguard container. I choose 192.168.1.8/29 subnet for my macvlans
        # ports:
        #     - 53:53/tcp
        #     - 53:53/udp
        #     - 67:67/udp
        #     - 68:68/udp
        #     - 68:68/tcp
        #     - 3000:3000/tcp
        #     - 80:80/tcp
        #     - 443:443/tcp
        dns:
            - ${dns1}
            - ${dns2}
        environment:
            - TZ=$tzone # your TZ
            - PUID=${puid}
            - GUID=${guid}
        volumes:
            - ${app_data}/adguard/work:/opt/adguardhome/work
            - ${app_data}/adguard/conf:/opt/adguardhome/conf
#            - /volume1/docker/acme/config/<cert_path>:/opt/adguardhome/cert #this string is needed if you want to use ACME issued HTTPS cert
        restart: unless-stopped

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
#        ports:
#            - 53:53/tcp
#            - 53:53/udp
#            - 67:67/udp
#            - 80:80/tcp
#            - 443:443/tcp
        environment:
            - TZ=$tzone
# WEBPASSWORD: 'set a secure password here or it will be random'
# Volumes store your data between container upgrades
        volumes:
            - ${app_data}/pihole/etc-pihole/:/etc/pihole/
            - ${app_data}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
# Recommended but not required (DHCP needs NET_ADMIN)
#   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        cap_add:
            - NET_ADMIN
        restart: always
        networks:
          macvlan_network:
            ipv4_address: ${ip2}
#        network_mode: host
#        networks:
#            - private
#Dont forget to turn on promiscuous mode on vSwitch    
networks:
  macvlan_network:
    name: macvlan_network
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: ${int}
    ipam:
      config:
        - subnet: ${sub}
          gateway: ${gate}
          ip_range: ${range}
